---
# Source: F5Demo/templates/configmap.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-plus-as3-configmap
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.1.0",
        "id": "nginx-plus",
        "label": "CIS AS3 Example",
        "remark": "Example of using CIS",
       "Common": {
          "class": "Tenant",
          "Shared": {
            "class": "Application",
            "template": "shared",
            "XFF_HTTP_Profile": {
              "class": "HTTP_Profile",
                "xForwardedFor": true
               }       
                

       }
       },
        "AS3": {
          "class": "Tenant",
          "MyApps": {
             "class": "Application",
             "template": "generic",
             "ingress": {
                "class": "Service_HTTP",
                "virtualAddresses": ["10.1.10.10"],
               
               "virtualPort": 80,
               "remark":"ingress: f5demo.waf.http.v1",	       
               "pool": "ingress_pool",
               "profileHTTP":{"use": "/Common/Shared/XFF_HTTP_Profile"},
               "policyWAF":{"bigip":"/Common/linux-low"},
               "securityLogProfiles": [
               {
                 "bigip": "/Common/Log all requests"
               }
               ]
             },
             "ingress_pool": {
                "class": "Pool",
                "monitors": [
                   "http"
                ],
                "members": [{
                   "servicePort": 80,
                   "serverAddresses": [
                   ]
                }]
             },
             "ingresstls": {
                "class": "Service_HTTPS",
                "virtualAddresses": ["10.1.10.10"
                ],
               
               "virtualPort": 443,
               "remark":"ingresstls: f5demo.waf.https.v1",
               "pool": "ingresstls_pool",
               "redirect80": false,
               "profileHTTP":{"use": "/Common/Shared/XFF_HTTP_Profile"},
               "serverTLS": {"bigip":"/Common/clientssl"},
               "clientTLS": {"bigip":"/Common/serverssl"},
               "policyWAF": {"bigip":"/Common/linux-high"},
               "securityLogProfiles": [
                 {
                   "bigip": "/Common/Log all requests"
                 }                  
               ]
             },
             "ingresstls_pool": {
                "class": "Pool",
                "monitors": [
                   "https"
                ],
                "members": [{
                   "servicePort": 443,
                   "serverAddresses": [
                   ]
                }]
             },
             "dashboard": {
                "class": "Service_HTTP",
                "virtualAddresses": ["10.1.10.10"
                ],
               
               "virtualPort": 8080,
               "remark":"dashboard: f5demo.http.v1",
               "pool": "dashboard_pool",
               "profileHTTP":{"use": "/Common/Shared/XFF_HTTP_Profile"}
             },
             "dashboard_pool": {
                "class": "Pool",
                "monitors": [
                   "http"
                ],
                "members": [{
                   "servicePort": 80,
                   "serverAddresses": [
                   ]
                }]
             }
       }
       }
    }
    }
