apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-dashboard
  namespace: nginx-ingress
  labels:
    cis.f5.com/as3-tenant: AS3
    cis.f5.com/as3-app: MyApps
    cis.f5.com/as3-pool: dashboard_pool
spec:
  type: NodePort
  ports:
  - port: 8181
    targetPort: 8181
    protocol: TCP
    name: http
  selector:
    app: nginx-ingress
