apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-tls
  namespace: nginx-ingress
  labels:
    cis.f5.com/as3-tenant: AS3
    cis.f5.com/as3-app: MyApps
    cis.f5.com/as3-pool: ingresstls_pool
spec:
  type: NodePort 
  ports:
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: nginx-ingress
